"""Lessons 1–34: one per chapter, titles from the book's contents (Appendix G map).

Each lesson: a goal, the levels it suits, three to seven steps pointing at the
real screens (registry slugs), an exercise computed in code on synthetic data,
and "Check my work" lines. Numbers the book prints are recomputed here, never
typed in as answers.
"""

from __future__ import annotations

import math
from collections.abc import Callable

from . import calc as c
from .model import Check, Exercise, Lesson, Step

S, E, B = "Starter", "Explorer", "Builder"


def N(key: str, text: str, fn: Callable[[str], float], tol: float = 0.01,
      unit: str = "") -> Check:
    return Check(key, text, "number", expected=fn, tol=tol, unit=unit)


def ST(key: str, text: str, fn: Callable[[], tuple[bool, str]]) -> Check:
    return Check(key, text, "state", state=fn)


def T(key: str, text: str) -> Check:
    return Check(key, text, "tick")


def facts(title: str, *lines: str) -> Callable[[str], Exercise]:
    return lambda market: Exercise(title, list(lines))


def const(x: float) -> Callable[[str], float]:
    return lambda market: x


LESSONS: tuple[Lesson, ...] = (
    Lesson(1, "What AI Actually Is — For a Trader",
           "See the difference between a number the model remembers and one the lab reads from data.",
           (S,),
           (Step("Pick your market with the top-bar switch: IN for NIFTY or US for SPY."),
            Step("Check the AI status: it names the model and says Local or Cloud."),
            Step("Read the previous close from the sample table below — a number from data, "
                 "not from the model's memory."),
            Step("Compute the five-day percentage change yourself, then Check my work."),
            Step("Ask for an explanation with Explain; use Second opinion to review it.")),
           (N("close", "Last close in the sample (29 May 2026)", c.last_close),
            N("five_day", "Five-day % change (last close ÷ close five bars earlier − 1)",
              c.five_day_change, 0.05, "%"),
            T("scorecard", "Your frontier-probe scorecard has an official source next to every "
                           "price, date and hours answer.")),
           c.ex_close_table),
    Lesson(2, "Choosing Your AI Assistant",
           "Route personal work to a local model, allow cloud only where data is public, and cap spend.",
           (S, E),
           (Step("Open Settings › AI Models; the wizard's local model is marked Default.", "ai-models"),
            Step("Click Test model and read its speed and accuracy line.", "ai-models"),
            Step("Optional: add a cloud key in Settings › Keys, then Add cloud model.", "keys"),
            Step("In Use for, set Journal and Portfolio to Local only.", "ai-models"),
            Step("Set a Monthly budget; cloud calls pause when it is reached.", "ai-models"),
            Step("In Settings › Privacy, switch on Ask before sending to cloud.", "privacy")),
           (ST("local", "Journal and Portfolio are set to Local only",
               lambda: c.use_for_local("Journal", "Portfolio")),
            ST("budget", "A monthly budget is set", c.budget_set),
            ST("ask", "Ask before sending to cloud is on", c.ask_before_cloud),
            T("keys", "No API key, token or password exists in any chat history.")),
           facts("Where each section's AI calls may go",
                 "Journal, Portfolio, Tax and Documents default to Local only",
                 "Cloud calls pause at the monthly budget and fall back to the local model")),
    Lesson(3, "Prompting for Money Work",
           "Run a quote-first read, fence pasted text, and recompute every growth figure yourself.",
           (S, E),
           (Step("Open Lessons › Prompt Library and search `concall` or `10-K`.", "prompts"),
            Step("Click Fill in: the placeholders become fields; pasted text is fenced UNTRUSTED.",
                 "prompts"),
            Step("Click Send to Document Desk and open two cited pages.", "documents"),
            Step("If you edited the prompt, click Save my version (tagged MY VERSION).", "prompts")),
           (N("kaveri", "Kaveri revenue growth: 412 ÷ 365 − 1", const(round((412 / 365 - 1) * 100, 1)),
              0.05, "%"),
            N("northwind", "Northwind growth: 1,284.6 ÷ 1,197.3 − 1",
              const(round((1284.6 / 1197.3 - 1) * 100, 1)), 0.05, "%"),
            T("quotes", "Every number in the answer appears word for word in its QUOTES section."),
            T("fenced", "Pasted web text was fenced and SUSPICIOUS TEXT says “none found” or names it.")),
           facts("Figures quoted from the fictional sample documents",
                 "Kaveri Pumps revenue: 412 (this year) vs 365 (last year), ₹ crore",
                 "Northwind net sales: 1,284.6 vs 1,197.3, $ million")),
    Lesson(4, "Setting Up Your AI Trading Lab",
           "Finish the wizard, read the four top-bar signals in both markets and keep privacy defaults.",
           (E, B),
           (Step("On Home, finish the first-run wizard: Pull model, Skip for now, Load sample data, "
                 "Run self-test.", "home"),
            Step("Read the top bar: market, data status, AI status, cost meter."),
            Step("Flip the switch to US and load the US sample too.", "home"),
            Step("Open Settings › Keys: any key shows only its last four characters.", "keys"),
            Step("Open Settings › Privacy: defaults on, Education lag 90 days.", "privacy"),
            Step("Generate the sample Daily Briefing and click Show sources.", "briefing")),
           (ST("selftest", "The self-test passed", c.self_test_passed),
            ST("markets", "You loaded the sample in both markets", c.both_markets_loaded),
            ST("privacy", "Privacy defaults are on and Education lag reads 90 days",
               c.privacy_defaults),
            ST("keys", "No key value sits in a text file", c.keys_masked),
            N("spy", "Builder: number of SPY bars from 2026-01-01 to 2026-05-29 (`spy.height`)",
              lambda m: c.spy_bars_2026(), 0)),
           facts("The four top-bar signals",
                 "Market switch: IN | US", "Data status: source and age",
                 "AI status: model with Local or Cloud", "Cost meter: this month's cloud spend")),
    Lesson(5, "Your Market Data — Free, India & US",
           "Compare two sources for one month and account for every flag over 0.5%.",
           (E, B),
           (Step("Open Settings › Data Sources and read the three tiers.", "data-sources"),
            Step("Open Compare sources; pick the symbol and 1–29 May 2026.", "data-sources"),
            Step("Read the summary: rows compared, missing dates, rows over 0.5%."),
            Step("Count the flags in the lesson table below, then Check my work.")),
           (N("disagree", "Rows over the 0.5% tolerance", lambda m: c.compare_counts(m)["disagree"], 0),
            N("missing", "Missing dates", lambda m: c.compare_counts(m)["missing"], 0),
            T("keys", "No key or token appears in any chat, screenshot or repository.")),
           c.ex_compare),
    Lesson(6, "Connecting AI to Your Broker — Safely",
           "Read every tool list, label each tool READ, PAPER or REAL-MONEY, and test the gap.",
           (E,),
           (Step("Open Settings › MCP Server: every tool is tagged READ or PAPER.", "mcp"),
            Step("Click Copy config for Claude Desktop and paste it there.", "mcp"),
            Step("Ask for a real order: no tool can place one."),
            Step("Ask for a paper order; Accept or Reject it in the Paper Desk.", "paper-desk"),
            Step("Open the Tool-call log and match it to what you approved.", "mcp")),
           (N("read", "How many PlugAI-Trade MCP tools are tagged READ?", lambda m: c.mcp_read_tools(), 0),
            T("gap", "The “place a real order” test returned no tool."),
            T("always", "No tool that can place, modify or cancel a real order is set to Allow always.")),
           facts("MCP server", "Tools are READ or PAPER; paper_order creates a pending paper order",
                 "The app contains no order code")),
    Lesson(7, "The Morning Briefing",
           "Generate a sourced, timed briefing and check a watchlist percentage by hand.",
           (S, E),
           (Step("Open Today › Daily Briefing and set the market.", "briefing"),
            Step("Click Generate briefing and read the four panels.", "briefing"),
            Step("Click Show sources on two lines and match their numbers.", "briefing"),
            Step("Click Schedule to run it before you wake up.", "briefing")),
           (N("pct", "Change as a percentage: 103.35 ÷ 24,610.00",
              const(round(103.35 / 24_610.00 * 100, 2)), 0.005, "%"),
            T("cutoff", "No line in the briefing is newer than the cutoff printed at the top."),
            T("advice", "No sentence says buy, sell, hold, target or “likely to”.")),
           facts("Watchlist line from the chapter", "NIFTY previous close 24,610.00, change +103.35")),
    Lesson(8, "Reading Faster: Results, Filings & Concalls",
           "Extract quotes with page numbers and compute every growth rate outside the model.",
           (S, E),
           (Step("Open Research › Document Desk and load a fictional sample.", "documents"),
            Step("Ask a question; answers list quotes first, each with a page chip.", "documents"),
            Step("Click Extract to table with the Red-flag checklist template.", "documents"),
            Step("Export CSV and compute growth in a sheet (or below).", "documents")),
           (N("receivables", "Kaveri receivables growth: 352 ÷ 280 − 1",
              const(round((352 / 280 - 1) * 100, 1)), 0.05, "%"),
            N("apple", "Apple net sales growth: 391,035 ÷ 383,285 − 1",
              const(round((391_035 / 383_285 - 1) * 100, 1)), 0.05, "%"),
            T("pages", "You opened at least two cited pages and the quotes match exactly.")),
           facts("Figures quoted in the chapter", "Kaveri receivables: 352 vs 280 (₹ crore)",
                 "Apple net sales FY2024 vs FY2023: 391,035 vs 383,285 ($ million)")),
    Lesson(9, "Screening & Watchlists in Plain English",
           "Turn a sentence into rules, check a known pass and fail by hand, save a reasoned watchlist.",
           (S, E),
           (Step("Open Research › Screener; choose the universe and As of date.", "screener"),
            Step("Type the idea in Describe your screen and read the Rules preview.", "screener"),
            Step("Click Run; check one pass and one fail against the rules.", "screener"),
            Step("Save as watchlist with a Reason and a Review by date.", "screener"),
            Step("Test a vendor score point-in-time in Score-Tester.", "score-tester")),
           (N("dist", "Sample index: distance of the last close from its 252-day high",
              c.dist_from_high, 0.05, "%"),
            T("reasons", "Every watchlist name has a reason, a source and a review date.")),
           c.ex_last_bars),
    Lesson(10, "Charts, Levels & Indicators with AI",
           "Describe a chart from its numbers and recompute one level by hand.",
           (S, E),
           (Step("Open Research › Chart Helper; symbol NIFTY or SPY, Daily.", "chart-helper"),
            Step("Click Describe, then Show sources; match two numbers.", "chart-helper"),
            Step("Click Levels and check one zone in the table.", "chart-helper"),
            Step("Compare the Screenshot mode answer, marked ✓ / ✗.", "chart-helper")),
           (N("pivot", "Pivot P = (H + L + C) ÷ 3 from the last sample bar", c.pivot, 0.05),
            T("nopattern", "No pattern name, direction call or target crept into the description.")),
           c.ex_last_bars),
    Lesson(11, "From Idea to Rules to Backtest",
           "Turn a sentence into rule cards, check the read-back, and cost one round trip by hand.",
           (E, B),
           (Step("Open Strategy › Strategy Builder and describe the idea.", "strategy-builder"),
            Step("Fill every assumed field; FILL defaults to the next open.", "strategy-builder"),
            Step("Read back in English, then Chart check.", "strategy-builder"),
            Step("Backtest, then read the Report Card and the Trials counter.", "backtest-report")),
           (N("cost", "Delivery round trip charges: buy ₹1,00,000, sell ₹1,02,000 (dated table)",
              lambda m: c.delivery_round_trip(), 1.0, "₹"),
            ST("trials", "The Trials counter recorded at least one test", c.trials_recorded),
            T("walk", "You read the walk-forward windows and trial count before the headline return.")),
           lambda m: Exercise("India delivery charges (dated table)",
                              [f"{k}: ₹{v:,.2f}" for k, v in
                               c.costs.india_round_trip(100_000, 102_000, "delivery").items()])),
    Lesson(12, "Planning the Trade & Sizing the Position",
           "Write a plan, size from the stop, and put your limits on a Rule Card.",
           (S, E),
           (Step("Open Plan & Risk › Trade Plan and click New plan.", "trade-plan"),
            Step("Click Critique and answer each question in the plan.", "trade-plan"),
            Step("Size it in the Position Sizer and Use in plan.", "position-sizer"),
            Step("Rule Card: New version, then Sync limits.", "rule-card")),
           (N("lots", "Lots: 15,000 ÷ 10,950, rounded down", const(math.floor(15_000 / 10_950)), 0),
            N("daily", "Daily loss limit in money on the default Rule Card (2R)",
              c.rule_card_daily_limit, 1.0),
            T("stop", "The stop came from the market and the size from the stop.")),
           facts("Sizing inputs from the chapter", "Budget (1R): ₹15,000",
                 "Stop distance × lot + costs: ₹10,950 per lot")),
    Lesson(13, "Paper Trading with Live Free Data",
           "Run a paper round trip and recompute its net result from the dated cost table.",
           (E,),
           (Step("Settings › Data Sources: Live stream, or use Replay.", "data-sources"),
            Step("Trade Plan: Send to Paper Desk.", "trade-plan"),
            Step("Paper Desk: Place paper order, then Close at next bar.", "paper-desk"),
            Step("Press the Kill switch once with no positions open.", "paper-desk"),
            Step("Set alerts From plan; every message starts with SIMULATED.", "alerts")),
           (N("net", "Net result of the paper round trip after charges", c.paper_net, 0.5),
            T("kill", "You pressed the kill switch once on purpose.")),
           c.ex_paper, samples=("paper",)),
    Lesson(14, "The AI Trading Journal & Weekly Review",
           "Import a month of trades, match totals with the broker, then review one change.",
           (S, E),
           (Step("Journal › Trades: this lesson loads Kavita's and Marcus's synthetic journals.",
                 "trades"),
            Step("Match plans and check the charges column.", "trades"),
            Step("Weekly Review: Generate review, Show sources, Save review.", "weekly-review"),
            Step("Ask My Journal: read the query line before the answer.", "ask-journal")),
           (N("count", "Round trips in the lesson journal", c.journal_count, 0),
            N("net", "Net result (sum of the net column)", c.journal_net, 1.0),
            T("thirty", "Any pattern you act on rests on 30 or more trades.")),
           c.ex_journal, samples=("kavita", "marcus")),
    Lesson(15, "Long-Term Investing & SIPs with AI",
           "Review a portfolio with the numbers on screen and project a goal under stated assumptions.",
           (S, E),
           (Step("Portfolio › Portfolio Reviewer: Import holdings (or the sample).", "portfolio"),
            Step("Open Overlap, Costs, Concentration and Allocation.", "portfolio"),
            Step("SIP planner: three assumed returns (6/8/10%), then Save plan.", "portfolio"),
            Step("Thesis tracker: Add thesis, then Check thesis.", "portfolio")),
           (N("sip", "Value of ₹15,000 a month for 15 years at an assumed 8% (illustrative)",
              lambda m: c.sip_value(), 1.0),
            T("three", "Your projection shows at least three assumptions, each labelled illustrative.")),
           facts("SIP assumptions (illustrative, not a forecast)", "Monthly amount: 15,000",
                 "Years: 15", "Assumed return: 8% a year, monthly compounding, month-end deposits")),
    Lesson(16, "ETFs, Sector Rotation & Dividend Income",
           "Measure an ETF's tracking difference and test rotation with costs, trials and tax.",
           (S, E),
           (Step("Portfolio Reviewer › ETF check: Add ETF and read the tiles.", "portfolio"),
            Step("Trend Lab › Rotation preset: Run, then the Parameter heatmap.", "trend-lab"),
            Step("Send to Backtest Report and read the grade.", "backtest-report"),
            Step("Send to Paper Desk for a three-month paper sleeve.", "paper-desk")),
           (N("td", "Tracking difference: fund 11.62% − index total return 12.10%",
              const(round(11.62 - 12.10, 2)), 0.005, " pts"),
            T("four", "Your rotation test reports costs, unseen years, trials and after-tax.")),
           facts("One year, same dates", "Fund return: 11.62%", "Index total return: 12.10%")),
    Lesson(17, "Swing Trading",
           "Screen with events excluded, size with an ATR stop, and turn plans into alerts.",
           (E,),
           (Step("Screener › Presets › Swing · Pullback; Exclude events within 5–10 sessions.",
                 "screener"),
            Step("Trade Plan: Weekend swing plan template.", "trade-plan"),
            Step("Position Sizer › ATR stop; confirm the size and Use in plan.", "position-sizer"),
            Step("Alerts: New alert → From plan, with an expiry.", "alerts")),
           (N("stop", "ATR stop: 616.50 − 1.5 × 12.79", const(round(616.50 - 1.5 * 12.79, 2)), 0.006),
            N("size", "US size: the smaller of 300 ÷ 1.17 and 6,000 ÷ 41.15, rounded down",
              lambda m: c.swing_size(), 0),
            T("expiry", "Every plan has a trigger expiry, invalidation and an events line.")),
           facts("Chapter inputs", "India: trigger ₹616.50, ATR(14) ₹12.79, multiple 1.5",
                 "US: $30,000 at 1% = $300 risk; stop distance $1.17; cap $6,000; trigger $41.15")),
    Lesson(18, "Positional Trading & Trend Following",
           "Size a trend rule by volatility and read the drawdown story before the return.",
           (E, B),
           (Step("Strategy › Trend Lab: MA crossover 50/200, Weekly check.", "trend-lab"),
            Step("Volatility sizing: sleeve, 12% target, 10% buffer, 100% cap.", "trend-lab"),
            Step("Parameter heatmap: look at the whole map.", "trend-lab"),
            Step("Send to Backtest Report: drawdown depth, start, months below high.",
                 "backtest-report")),
           (N("units", "Units: sleeve × 12% ÷ 16 ÷ daily move ÷ price, rounded down", c.vol_units, 1),
            T("plateau", "Your setting sits on a plateau of the heatmap, not a lone peak.")),
           c.ex_vol),
    Lesson(19, "Earnings & Event Trading",
           "Compare the implied move with history and split out the event.",
           (E,),
           (Step("Research › Earnings Desk › Results calendar: Import watchlist.", "earnings"),
            Step("Results digest: Generate digest; check the Change column.", "earnings"),
            Step("Implied vs historical move: read the tiles.", "earnings"),
            Step("Open in Options Strategy Builder to test scenarios.", "options")),
           (N("implied", "Implied move: (3.35 + 3.15) ÷ 84.20", const(round(6.50 / 84.20 * 100, 1)),
              0.05, "%"),
            N("avg", "Average of the eight absolute moves: 46.9 ÷ 8", const(round(46.9 / 8, 1)),
              0.05, "%")),
           facts("Lakeshore (fictional)", "Call 3.35, put 3.15, price 84.20",
                 "Sum of the last eight absolute moves: 46.9%")),
    Lesson(20, "IPO Trading",
           "Build an RHP digest with page chips and estimate allotment odds in code.",
           (S, E),
           (Step("Research › IPO Dashboard › RHP digest: Extract to table.", "ipo"),
            Step("Subscription: read category rows; Allotment odds after close.", "ipo"),
            Step("SME checker: Run checks; open every not-found row.", "ipo"),
            Step("Listing-day plan: Critique, Lock-in calendar, Save to journal.", "ipo")),
           (N("ofs", "OFS share: 2.1 crore of 3.5 crore shares", const(2.1 / 3.5 * 100), 0.05, "%"),
            N("pe", "Post-issue P/E: ₹284 ÷ (₹96 crore ÷ 11.4 crore shares)",
              const(round(284 / round(96 / 11.4, 2), 1)), 0.05),
            N("odds", "Retail odds: 2,45,000 lots ÷ 24,60,000 applications",
              const(round(245_000 / 2_460_000 * 100, 2)), 0.01, "%")),
           facts("Issue figures (fictional)", "Shares offered 3.5 crore, of which OFS 2.1 crore",
                 "Profit ₹96 crore, 11.4 crore shares post-issue, price ₹284",
                 "Retail lots 2,45,000; valid applications 24,60,000")),
    Lesson(21, "Intraday & Scalping",
           "See the toll on every paper ticket and write your intraday guardrails once.",
           (E,),
           (Step("Screener › Presets › Gap scan, then Schedule.", "screener"),
            Step("Chart Helper › Levels › Intraday; Send levels to Paper Desk.", "chart-helper"),
            Step("Paper Desk: read Cost preview and Breakeven (pts).", "paper-desk"),
            Step("Rule Card: Intraday guardrails, Accept, Sync limits.", "rule-card")),
           (N("toll", "Toll in points: (charges 960.85 + slippage 130) ÷ one lot's point value",
              lambda m: round((960.85 + 130) / c.nifty_lot(), 2), 0.01, " pts"),
            T("blocked", "One deliberate test order was blocked and logged as BLOCKED.")),
           lambda m: Exercise("NIFTY one-lot toll",
                              [(f"Lot size {c.nifty_lot()} (reference tables as of "
                                f"{c.reference.as_of()})"), "Charges ₹960.85, slippage ₹130"])),
    Lesson(22, "Options Buying — Know What You're Paying For",
           "Read what a call really charges you: breakeven, required move and expected move.",
           (E, B),
           (Step("Derivatives › Options Strategy Builder: Add leg → Buy → Call.", "options"),
            Step("Read What you're paying for; drag Days left from 5 to 1.", "options"),
            Step("Scenarios: Gap, then IV spike.", "options"),
            Step("Save to plan with your exit rule in words.", "options")),
           (N("be", "Breakeven: strike 25,000 + premium 89", const(25_000 + 89), 0.5),
            N("sigma", "Expected ±1σ: 24,800 × 0.14 × √(5 ÷ 365)",
              const(round(24_800 * 0.14 * math.sqrt(5 / 365))), 1.0),
            T("lot", "The lot size and expiry day match today's Contract Table, not memory.")),
           facts("NIFTY 25000 CE (lesson defaults)", "Spot 24,800 · premium ₹89 · IV 14% · 5 days"),
           samples=("options",)),
    Lesson(23, "Options Selling & Income Strategies",
           "Build an iron condor from a preset and recompute its maximum loss.",
           (E, B),
           (Step("Options Strategy Builder › Income presets › Iron condor.", "options"),
            Step("Read Credit, Max loss, both Breakevens and Margin estimate.", "options"),
            Step("Scenarios: the default set plus one uncomfortably large move.", "options"),
            Step("Send to Paper Desk for eight cycles.", "paper-desk")),
           (N("maxloss", "Condor max loss: (200 − 61.10) × lot",
              lambda m: round((200 - 61.10) * c.nifty_lot(), 2), 0.5, "₹"),
            T("stress", "The stress table's worst row fits your Rule Card.")),
           facts("Iron condor (lesson defaults)", "Wings 200 points wide",
                 "Net credit 61.10 points"), samples=("options",)),
    Lesson(24, "Futures & Commodities",
           "Simulate daily mark-to-market and put the roll on your calendar.",
           (S, E),
           (Step("Derivatives › Futures & Roll › Margin & MTM: Replay path.", "futures"),
            Step("Add shock −3% and read Move to margin call.", "futures"),
            Step("Roll calendar: Set roll alert.", "futures"),
            Step("Contract Table: check the lot and its as-of date.", "contract-table")),
           (N("mtm", "Day 4 MTM: (24,560 − 24,780) × lot", lambda m: (24_560 - 24_780) * c.nifty_lot(),
              0.5, "₹"),
            T("roll", "The roll date is on your calendar before the position is opened.")),
           facts("Settlement prices", "Day 3: 24,780", "Day 4: 24,560")),
    Lesson(25, "Crypto",
           "Price a perpetual's funding by hand and keep exchange keys read-only.",
           (S, E),
           (Step("Portfolio › Crypto Monitor › Funding rates: Add position.", "crypto"),
            Step("Read the tiles; check Funding times per day.", "crypto"),
            Step("Alerts: From Crypto Monitor with Quiet hours.", "alerts"),
            Step("Tax Export: the VDA ledger never nets losses.", "tax")),
           (N("day", "Day 1 funding on ₹5,00,000: 0.0064% + 0.0135% + 0.0108%",
              const(round(500_000 * (0.0064 + 0.0135 + 0.0108) / 100, 1)), 1.0, "₹"),
            N("annual", "Annualised: 0.0656% × 3 × 365", const(round(0.0656 * 3 * 365, 1)), 0.1, "%"),
            T("keys", "No exchange key held by a tool can trade or withdraw.")),
           facts("BTC perpetual (lesson)", "Notional ₹5,00,000, 10×",
                 "Day 1 funding prints: 0.0064%, 0.0135%, 0.0108%")),
    Lesson(26, "Currency, Pairs & Prediction Markets",
           "Test a pair on its formation window only and score forecasts with Brier.",
           (E, B),
           (Step("Contract Table: filter currencies; note Exposure required.", "contract-table"),
            Step("Position Sizer › Hedge.", "position-sizer"),
            Step("Pairs Lab: SYN-A / SYN-B, Find pairs, Check link, Spread z-score.", "pairs-lab"),
            Step("Forecast Journal (US): Add forecast with the price hidden.", "forecasts")),
           (N("hl", "Half-life of the SYN-A / SYN-B spread (sessions)", lambda m: c.half_life(), 0.05),
            N("brier", "One Brier term: forecast 0.7, outcome 0 → (0.7 − 0)²", const(0.49), 0.005),
            T("exits", "Three exits (target, time, break) were written before entry.")),
           facts("Lesson 26 sample", "SYN-A / SYN-B: synthetic, cointegrated by construction",
                 "Formation window: 250 sessions"), samples=("pairs",)),
    Lesson(27, "Let AI Write the Code",
           "Create a report plugin from the template and make every check green.",
           (B,),
           (Step("Automate › Plugins: New from template → Report, name gap_report.", "plugins"),
            Step("Open folder; let your assistant write plugin.py and one test.", "plugins"),
            Step("Run checks: every line green.", "plugins"),
            Step("Run on the NIFTY and SPY samples; then Enable.", "plugins")),
           (N("gap", "Gap of the last sample bar: open ÷ previous close − 1", c.gap_pct, 0.01, "%"),
            ST("plugin", "A plugin exists in your lab", c.plugin_created),
            T("broke", "Your test failed at least once when you broke the code on purpose.")),
           c.ex_last_bars),
    Lesson(28, "News & Sentiment Pipelines",
           "Stamp every headline with when it became tradable and measure the effect after costs.",
           (E, B),
           (Step("Automate › News Pipeline › Sources: Fetch now.", "news"),
            Step("Score with FinBERT and Local model; Compare scorers.", "news"),
            Step("Event study with a cost preset.", "news"),
            Step("Scheduler: fetch every 15 minutes, score overnight.", "scheduler")),
           (N("net", "Cost row: gross drift 31.5 bp − cost 20 bp", const(31.5 - 20), 0.05, " bp"),
            N("agree", "Agreement: diagonal (40 + 30 + 9) ÷ total 100", const(79.0), 0.05, "%"),
            T("cutoff", "Every language-model test used headlines after its training cutoff.")),
           facts("Scorer agreement (lesson table)", "Rows: pos/neu/neg by scorer A vs B",
                 "Diagonal: 40, 30, 9 · total 100")),
    Lesson(29, "Machine Learning Basics for Traders",
           "Split in time, beat the majority guess, and count every model as a trial.",
           (B,),
           (Step("Automate › ML Lab › Dataset: leave the Noise control on.", "ml-lab"),
            Step("Label: Direction, next 10 sessions; Split in time with Purge.", "ml-lab"),
            Step("Train baseline; compare with the majority guess.", "ml-lab"),
            Step("Shuffle test (for learning only), then Accept the model card.", "ml-lab")),
           (N("majority", "Majority-guess accuracy for “up over the next 10 sessions” on the sample",
              c.majority_share, 0.1, "%"),
            T("purge", "The purge is at least as long as the label's horizon.")),
           facts("The first baseline", "Label: next-10-session return above zero",
                 "Majority guess: always predict the more common class")),
    Lesson(30, "AI Agents & Research Teams",
           "Run an agent team, send its proposal through your own checks, and count its trials.",
           (B,),
           (Step("Automate › Plugins: Install an agent plugin at a pinned tag.", "plugins"),
            Step("Automate › Agents: team, subject, As-of date, Mask names, Budget.", "agents"),
            Step("Run; read the Transcript and the Proposal card.", "agents"),
            Step("Send to Strategy Builder; Read back, Chart check, Backtest.", "strategy-builder")),
           (ST("decided", "A proposal was accepted, rejected or sent on", c.proposal_decided),
            T("tools", "The plugin's tool list contains no order or paper-order tool."),
            T("trials", "The Trials counter includes the agent's own tests.")),
           facts("Agent output", "PROPOSAL · NOT AN ORDER", "Rules arrive tagged PROPOSED")),
    Lesson(31, "Private AI on Your Own Computer",
           "Pick models that fit your machine and keep personal sections Local only.",
           (E, B),
           (Step("Settings › AI Models: read your memory and the Fit check bar.", "ai-models"),
            Step("Set Context length; Test model for speed and reading time.", "ai-models"),
            Step("Embeddings: Pull model.", "ai-models"),
            Step("Use for: Journal, Portfolio, Tax and Documents → Local only.", "ai-models"),
            Step("Document Desk › My library: Add folder, Ask my documents.", "documents"),
            Step("Scheduler: Add job, Run now, View log.", "scheduler")),
           (N("fit", "Fit check total for the 9B model at 8k context on 16 GB with 4 GB in use (GB)",
              lambda m: c.fit_total(), 0.05),
            ST("local", "Journal, Portfolio, Tax and Documents are Local only",
               lambda: c.use_for_local("Journal", "Portfolio", "Tax", "Documents"))),
           c.ex_fit),
    Lesson(32, "Tax Records with AI — India & US",
           "Classify every round trip by a rule, recompute turnover, and export a draft for your CA / CPA.",
           (S, E),
           (Step("Tax › Tax Export: Import tradebook (or the lesson sample).", "tax"),
            Step("Classify; rows the rules cannot place say ASK CA.", "tax"),
            Step("Turnover calculator; Reconcile AIS.", "tax"),
            Step("Export: stamped Draft for your CA / CPA.", "tax")),
           (N("turnover", "Turnover: sum of the ten per-trade values", const(sum(c.TURNOVER_ROWS)),
              0.5, "₹"),
            T("askca", "Rows marked ASK CA are listed in your note to the CA.")),
           facts("Per-trade turnover (₹)", ", ".join(f"{x:,}" for x in c.TURNOVER_ROWS)),
           samples=("meera",)),
    Lesson(33, "Staying Safe: Scams, Security & the Rules",
           "Run the security checklist, check registrations on the regulator's site, export the log.",
           (S,),
           (Step("Settings › Security: read the Security checklist.", "security"),
            Step("Tick the manual items yourself.", "security"),
            Step("Registration check: open the official register.", "security"),
            Step("Check a pitch; read the claims table.", "security"),
            Step("Audit log: filter Cloud, then Export log.", "security")),
           (N("compound", "The calculator test: 3% a day for 250 trading days multiplies the stake by",
              lambda m: round(1.03 ** 250), 1.0),
            ST("strip", "Cloud calls strip account numbers and PAN/SSN", c.strip_on),
            ST("export", "This month's audit log has been exported", c.audit_exported_this_month),
            T("register", "Everyone you pay was looked up on the regulator's own site.")),
           facts("A pitch from the chapter", "“AI bot, 3% a day, fixed”")),
    Lesson(34, "Your AI Trading System — Putting It All Together",
           "Apply a workspace template, keep a rhythm, and gate real money behind written pass marks.",
           (S, E),
           (Step("Settings › Workspace: Apply template, Preview changes, Accept per group.",
                 "workspace"),
            Step("Export workspace and keep it with your backups.", "workspace"),
            Step("Rule Card › Go / no-go: Run check on the Paper account.", "rule-card"),
            Step("Weekly Review every week; monthly audit on the first weekend.", "weekly-review")),
           (ST("workspace", "A workspace template is applied", c.workspace_applied),
            ST("update", "Reference tables are less than a month old", c.tables_fresh),
            T("marks", "Your go/no-go pass marks were written before the paper period."),
            T("pilot", "Your pilot plan names a budget, a size computed in code, a review date and "
                       "stop conditions.")),
           facts("The rhythm", "Daily ≈ 10 min before the open and 10 after",
                 "Weekly review 30 min", "Monthly audit", "Quarterly tax records")),
)
