// Mirrors src/plugai_trade/app/registry.py — names are the book's.
export interface Screen { section: string; title: string; slug: string; ready?: boolean }
export const SCREENS: Screen[] = [
  { section: "Today", title: "Daily Briefing", slug: "briefing" },
  { section: "Research", title: "Document Desk", slug: "documents" },
  { section: "Research", title: "Screener", slug: "screener" },
  { section: "Research", title: "Score-Tester", slug: "score-tester" },
  { section: "Research", title: "Chart Helper", slug: "chart-helper" },
  { section: "Research", title: "Earnings Desk", slug: "earnings" },
  { section: "Research", title: "IPO Dashboard", slug: "ipo" },
  { section: "Strategy", title: "Strategy Builder", slug: "strategy-builder" },
  { section: "Strategy", title: "Backtest Report", slug: "backtest-report", ready: true },
  { section: "Strategy", title: "Trend Lab", slug: "trend-lab" },
  { section: "Strategy", title: "Pairs Lab", slug: "pairs-lab" },
  { section: "Plan & Risk", title: "Trade Plan", slug: "trade-plan" },
  { section: "Plan & Risk", title: "Position Sizer", slug: "position-sizer" },
  { section: "Plan & Risk", title: "Rule Card", slug: "rule-card" },
  { section: "Paper Trading", title: "Paper Desk", slug: "paper-desk", ready: true },
  { section: "Paper Trading", title: "Alerts", slug: "alerts" },
  { section: "Derivatives", title: "Options Strategy Builder", slug: "options", ready: true },
  { section: "Derivatives", title: "Futures & Roll", slug: "futures" },
  { section: "Derivatives", title: "Contract Table", slug: "contract-table" },
  { section: "Portfolio", title: "Portfolio Reviewer", slug: "portfolio" },
  { section: "Portfolio", title: "Crypto Monitor", slug: "crypto" },
  { section: "Portfolio", title: "Forecast Journal", slug: "forecasts" },
  { section: "Journal", title: "Trades", slug: "trades" },
  { section: "Journal", title: "Weekly Review", slug: "weekly-review" },
  { section: "Journal", title: "Ask My Journal", slug: "ask-journal" },
  { section: "Tax", title: "Tax Export", slug: "tax" },
  { section: "Automate", title: "Scheduler", slug: "scheduler" },
  { section: "Automate", title: "News Pipeline", slug: "news" },
  { section: "Automate", title: "ML Lab", slug: "ml-lab" },
  { section: "Automate", title: "Agents", slug: "agents" },
  { section: "Automate", title: "Plugins", slug: "plugins" },
  { section: "Lessons", title: "Lessons", slug: "lessons" },
  { section: "Lessons", title: "Prompt Library", slug: "prompts" },
  { section: "Settings", title: "Data Sources", slug: "data-sources" },
  { section: "Settings", title: "AI Models", slug: "ai-models" },
  { section: "Settings", title: "Keys", slug: "keys" },
  { section: "Settings", title: "MCP Server", slug: "mcp" },
  { section: "Settings", title: "Privacy", slug: "privacy" },
  { section: "Settings", title: "Security", slug: "security" },
  { section: "Settings", title: "Workspace", slug: "workspace" },
];
export const SECTIONS = [...new Set(SCREENS.map((s) => s.section))];
